# Usa una imagen base oficial de Node.js
FROM node:18-alpine

# Configura el directorio de trabajo
WORKDIR /app

# Copia el archivo de definición de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Expone el puerto en el que la app correrá
EXPOSE 5050

# Comando para ejecutar la aplicación
CMD ["node", "src/app.js"]
