# Usa una imagen base oficial de Node.js
FROM node:18-alpine

# Configura el directorio de trabajo
WORKDIR /app

# Copia el archivo de definición de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Construye el frontend
RUN npm run build

# Expone el puerto en el que la app correrá
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["serve", "-s", "build"]
